### PR TITLE
Update stylus-brunch to our fork

### PR DESCRIPTION
**Pull request by adammcmaster**

### CODE REVIEW

**Comment by srallen** [comment]
The error was actually a syntax issue in one of the stylus files. I got this to work using the npm package, so I don't think this is necessary.

**Comment by eatyourgreens** [comment]
This is fixed in #160.

**Comment by marten** [comment]
#6 isn't a PR so it can't fix anything. But the zooniverse fork doesn't seem to exist anymore either so whatever.

**Comment by adammcmaster** [comment]
I still have a copy of the Zooniverse-owned fork if you need it

**Comment by marten** [comment]
Yeah could you reupload it?

**Comment by adammcmaster** [comment]
Sure https://github.com/zooniverse/stylus-brunch/tree/rgz-fork

**Pull request closed without merging**
